spring:
  application:
    name: provider-order
  session:
    store-type: none
server:
  tomcat:
    max-connections: 2000
    max-threads: 1000
    accept-count: 600
    uri-encoding: UTF-8

# security.basic.enabled: false

## apple cloud security config
apple.security.browser.loginPage: /order-login.html #默认登录页
apple.security.browser.loginType: JSON #登录成功或失败返回信息(JSON)或者跳转到原请求url(REDIRECT)

