spring:
  application:
    name: provider-order
  session:
    store-type: none
server:
  tomcat:
    max-connections: 2000
    max-threads: 1000
    accept-count: 600
    uri-encoding: UTF-8

# security.basic.enabled: false

## apple cloud security config
apple.security.browser.loginPage: /order-login.html #默认登录页
apple.security.browser.loginType: JSON #登录成功或失败返回信息(JSON)或者跳转到原请求url(REDIRECT)

## 验证码的配置
apple.security.code.image.width: 67 #验证码图形宽度
apple.security.code.image.height: 23 #验证码图形高度
apple.security.code.image.length: 6 #验证码长度
apple.security.code.image.expireIn: 60 #过期时间,单:秒
apple.security.code.image.urlAndMethods: /order/*,/teacher:put #需要验证码的请求url+method
