server:
  port: 9002

sharding:
  jdbc:
    datasource:
      ds_0:
        name: master
        filters: config
        url: jdbc:mysql://localhost:3306/ds_msg?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: hg4uZEbdFWp7NIfeJfIAjyEFvcaJ5wmT+/GC/921N0yTOfSwrMMeG6Rs7XOsjrdhR2rOBzEkdB0RNU5oagu/5A==
        publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMZQbZXVGlg+cTJvBphpyxqiNznKh2pXlsULm+v6fEmrKCMNhPIThFbP30+bpfx3Rh0BHpc/gxvyPlSTb3Jmb40CAwEAAQ==

rocketmq:
  group: apple-cloud-group
  namesrv: apple01:9876 # name-server1-ip:9876;name-server2-ip:9876 注意是分号分割

spring:
  redis:
    host: apple01
    port: 6379
  kafka:
      bootstrap-servers: kafka01:9092,kafka02:9092,kafka03:9092
      consumer:
        group-id: provider_msg