
jdbc:
  datasource:
    ds_msg:
      name: master
      filters: stat
      url: jdbc:mysql://localhost:3306/ds_msg?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root1234
      publickey: null

rocketmq:
  group: apple-cloud-group
  namesrv: apple01:9876 # name-server1-ip:9876;name-server2-ip:9876 注意是分号分割

spring:
  redis:
    cluster:
      nodes: 10.16.70.193:9000,10.16.70.194:9000,10.16.70.195:9000,10.16.70.193:10000,10.16.70.194:10000,10.16.70.195:10000
  kafka:
    bootstrap-servers: kafka01:9092
    consumer:
      group-id: provider_msg #固定


