defaultDataSourceName: ds_0
keyGeneratorClass: com.cachexic.cloud.config.sjdbc.keygen.IPKeyGenerator

tables:
  t_demo:  #逻辑表名
    actualTables: ds_${0..1}.t_demo_${0..1}
    generateKeyColumns:
      - columnName: id
    databaseStrategy:
      shardingColumns: id
      algorithmExpression: ds_${Math.floorMod(id.toString().hashCode(),2L)}
    tableStrategy:
      shardingColumns: id
      algorithmExpression: t_demo_${Math.floorMod(Math.floorDiv(id.toString().hashCode(),2L),2L)}

#默认数据库分片策略
defaultDatabaseStrategy:
  shardingColumns: none
  algorithmClassName: com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm
defaultTableStrategy:
  shardingColumns: none
  algorithmClassName: com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm

props:
  sql.show: true
  metrics.enable: false
