spring:
  application:
    name: center-eureka

security:
  basic:
    enabled: true
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000 #驱逐下线的服务，间隔,10秒

# http://localhost:8761/