security:
  user:
    name: user
    password: password123456

server:
  port: 8761

eureka:
  client:
    #register-with-eureka: false #单机不注册到自己
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:password123456@localhost:8761/eureka
